version: "3"

services:
  lsgd-react:
    container_name: lsgd-react
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "3000:3000"
