version: "3"

services:
  lsgd-react:
    container_name: lsgd-react
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
    # ports:
    #   - "3000:3000"
