version: "3"

services:
  my-react-app:
    container_name: lsgd-react
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
    ports:
      - "3000:3000"
