name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          script: |
            cd ~/lsgd-react/
            sudo git restore .
            sudo git pull
            sudo docker-compose -f ~/lsgd-react/docker-compose.prod.yml up --build --force-recreate --no-deps -d
            echo "done"
